title: Oh yu bhin
description: Game Developer
site_title: 'Oh yu bhin - Game Developer'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: eye2ffect
blog_url: https://muksal2000.tistory.com
email: green4072@naver.com
keybase_username: eye2ffect
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 